### ISSUE TITLE
HandleRoute and HandlePort refactoring

### ISSUE THREAD

**Issue by Konard** [deep-foundation/deeplinks#249]
# HandleRoute ports handling
Today it is impossible to open port on server using HandleRoute because `deeplinks` is launched with single opened port, for example:
https://github.com/deep-foundation/deeplinks/blob/00a1ca0ca51b3b25ba59a31ee2b4f1f410c0f55b/docker-prod/deep/docker-compose.yml#L122

That means we can only access `deeplinks` via 3006 port.

And in order to solve it we might use:
1. Restart the container with update to `docker-compose.yml` adding new port each time (this will require to restart the orchestrator itself, which I think is a bad idea, because it will break ongoing GQL and File connections).
2. Reserver ports range for the `deep-links` container. (this is also a bad idea, because if on server we have any post that is already in use in that range the `deep-links` container will be unable to start).
3. In any case we should monitor if each port is free in order to use it.
4. And the best solution as I see it right now is to use **`HandlePorts/HandleDocker`** for that.

# HandlePort ports handling
It is also not possible for HandlePort to use more than single port.

For example we could start a game server for `Ragnarok Online` that uses 3 different ports (login, char, map servers). We could also want to start an operating system with macOS, Linux, Windows and we might want to configure freely which ports are available to external network. We also might want to have universal way to monitor `healthz` of the docker container.

So the best solution would be to configure the port for `healthz` or full featured Deep-compatible controller that has rest or may be even GQL API? We need a way to transfer initial data, for example we might use `init` route to pass the token of the package that create that container to use it for operations. For example using the token passed via `init` we might create subscriptions to links that control the behaviour of docker container. Or may be we could create a mini-deep inside that would allow docker container control via the same Deep GQL API.

# HandleDocker/HandlePorts 

Once we have something like **HandleDocker/HandlePorts**, with support of multiple ports, we can move the responsibility for HandleRoute module there. So it in the separate docker and once port configuration is changed it may be restarted separately. It will also be better for performance scaling.

**Comment by Konard** [comment]
@Menzorg @ivansglazunov do you have any objections to these changes?

**Comment by suenot** [comment]
One port for docker container is good idea. Keep it simple, stupid.

**Comment by Konard** [comment]
> One port for one docker container is the good idea. Keep it simple, stupid.

Why do you think it is good idea? Why we cannot use multiple ports for docker? What would you do if the docker needs server in regular sockets and also a way to check its `healthz`? What would you do if use start macOS, Linux, Windows in docker container and need both SSH and VNC or RDP and HTTP? What if you want to use docker containers as a platform for self-organized hosting provider and so on?

And what would you do if you need multiple ports for HandleRoute? Where to host them? We should start a docker container for each port? But what if the logic inside needs two or more ports per process?

**Comment by suenot** [comment]
We can pass range of ports with `envsubst` command.
```
➜  export D_PORTS="'1111:80','2222:80'"                       
➜  cat docker-compose.yml                                     
version: "3"

services:
    client:
        image: nginx
        ports: [${D_PORTS}]
        volumes:
            - ./src:/usr/share/nginx/html%                                      
➜  envsubst '${D_PORTS}' < docker-compose.yml > docker-compose.subst.yml
➜  cat docker-compose.subst.yml
version: "3"

services:
    client:
        image: nginx
        ports: ['1111:80','2222:80']
        volumes:
            - ./src:/usr/share/nginx/html% ```
            
 And then we can run new file docker-compose.subst.yml:
```
docker-compose -f docker-compose.subst.yml up
```

This solution I found on [stackoverflow](https://stackoverflow.com/questions/50919605/docker-compose-variable-substitution-interpolation-with-list-map-or-array-va).
